// <auto-generated />
using System;
using Mep1.Erp.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mep1.Erp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260106233022_AddMustChangePasswordToTimesheetUser")]
    partial class AddMustChangePasswordToTimesheetUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Mep1.Erp.Core.ApplicationSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApplicationSubmissionDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinalPaymentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PayLessNoticeDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaymentNoticeDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RuleType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RuleValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValuationPeriodEnd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCode", "ApplicationSubmissionDate");

                    b.ToTable("ApplicationSchedules");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("GrossAmount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PaymentTermsDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VatAmount")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("VatRate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("ProjectCode");

                    b.HasIndex("Id");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRealProject")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobNameOrNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobNameOrNumber", "CompanyCode");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Mep1.Erp.Core.SupplierCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("Id", "SupplierId", "Date");

                    b.ToTable("SupplierCosts");
                });

            modelBuilder.Entity("Mep1.Erp.Core.TimesheetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreasJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CcfRef")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntryId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Hours")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LevelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UpdatedByWorkerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("WorkerId", "EntryId")
                        .IsUnique();

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("Mep1.Erp.Core.TimesheetUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("MustChangePassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Worker");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TimesheetUsers", (string)null);
                });

            modelBuilder.Entity("Mep1.Erp.Core.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Initials")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignatureCapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignatureName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Initials")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Mep1.Erp.Core.WorkerRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("RatePerHour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId", "ValidFrom");

                    b.ToTable("WorkerRates");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Invoice", b =>
                {
                    b.HasOne("Mep1.Erp.Core.Project", "Project")
                        .WithMany()
                        .HasForeignKey("Id");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Mep1.Erp.Core.SupplierCost", b =>
                {
                    b.HasOne("Mep1.Erp.Core.Project", "Project")
                        .WithMany("SupplierCosts")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mep1.Erp.Core.Supplier", "Supplier")
                        .WithMany("SupplierCosts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Mep1.Erp.Core.TimesheetEntry", b =>
                {
                    b.HasOne("Mep1.Erp.Core.Project", "Project")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mep1.Erp.Core.Worker", "Worker")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Mep1.Erp.Core.WorkerRate", b =>
                {
                    b.HasOne("Mep1.Erp.Core.Worker", "Worker")
                        .WithMany("Rates")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Project", b =>
                {
                    b.Navigation("SupplierCosts");

                    b.Navigation("TimesheetEntries");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Supplier", b =>
                {
                    b.Navigation("SupplierCosts");
                });

            modelBuilder.Entity("Mep1.Erp.Core.Worker", b =>
                {
                    b.Navigation("Rates");

                    b.Navigation("TimesheetEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
